---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item. The playbook contains a list of
# plays, with each play being a dictionary
-
  # Target: where our play will run and options it will run with
  hosts: webservers

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

    - name: loop through list
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
      tags:
        - install-epel

    - name: Install Nginx
      package:
        name: nginx
        state: latest
      tags:
        - install-nginx

    - name: Install patch
      yum:
        name: patch
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'
      tags:
        - patch-nginx
    - name: patch nginx.conf to include sites-availabe, disable default server entry
      patch:
        src: files/nginx.conf.centos.patch
        dest: /etc/nginx/nginx.conf
      when: ansible_distribution == 'CentOS'
      tags:
        - patch-nginx
    - name: Create /etc/nginx/sites-available directory if required
      file:
        path: /etc/nginx/sites-available
        state: directory
      tags:
        - patch-nginx
    - name: Create /etc/nginx/sites-enabled directory if required
      file:
        path: /etc/nginx/sites-enabled
        state: directory
      tags:
        - patch-nginx
    - name: Copy default nginx configuration
      copy:
        src: config/nginx-default.conf
        dest: /etc/nginx/sites-available/tamiltutapp
      tags:
        - patch-nginx
    - name: symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enabled/default
      file:
        src: /etc/nginx/sites-available/tamiltutapp
        dest: /etc/nginx/sites-enabled/tamiltutapp
        state: link
      tags:
        - patch-nginx

    - name: Create nginx/html directory if required
      file:
        path: /usr/share/nginx/html
        state: directory
      tags:
        - patch-nginx
    - name: Template index.html.j2 to index.html on target
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
      tags:
        - nginx-template
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      notify: Check HTTP Service
      tags:
        - nginx-running

    - name: Open CentOS firewall for Nginx
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_distribution == 'CentOS'
      notify: Reload Firewall
      tags:
        - nginx-open-firewall

# Handlers: handlers that are executed as a notify key from a task
  handlers:
    - name: Check HTTP Service
      uri:
        url: http://{{ ansible_default_ipv4.address}}
        status_code: 200
    - name: Reload Firewall
      service:
        name: firwalld
        state: reloaded

    
# Three dots indicate the end of a YAML document
...
